---
app_name: "{{ lookup('env', 'APP_NAME') or 'forklift' }}"
app_namespace: "{{ lookup( 'env', 'WATCH_NAMESPACE') or 'konveyor-forklift' }}"

image_registry: "{{ lookup( 'env', 'IMAGE_REGISTRY') }}"
image_org: "{{ lookup( 'env', 'IMAGE_ORG') }}"
image_pull_policy: Always

controller_repo: "{{ lookup( 'env', 'CONTROLLER_REPO') }}"
controller_image: "{{ image_registry }}/{{ image_org }}/{{ controller_repo }}"
controller_version: "{{ lookup( 'env', 'CONTROLLER_TAG') | default('latest') }}"
controller_image_fqin: "{{ controller_image }}:{{ controller_version }}"

ui_repo: "{{ lookup( 'env', 'UI_REPO') }}"
ui_image: "{{ image_registry }}/{{ image_org }}/{{ ui_repo }}"
ui_version: "{{ lookup( 'env', 'UI_TAG') | default('latest') }}"
ui_image_fqin: "{{ ui_image }}:{{ ui_version }}"

controller_configmap_name: "{{ controller_service_name }}-config"
controller_service_name: "{{ app_name }}-controller"
controller_deployment_name: "{{ controller_service_name }}"
controller_container_name: "{{ app_name }}-controller"
controller_container_limits_cpu: "100m"
controller_container_limits_memory: "800Mi"
controller_container_requests_cpu: "100m"
controller_container_requests_memory: "350Mi"

inventory_volume_path: "/var/cache/inventory"
inventory_container_name: "{{ app_name }}-inventory"
inventory_service_name: "{{ app_name }}-inventory"
inventory_route_name: "{{ inventory_service_name }}"

ui_oauth_user_scope: "user:full"
ui_configmap_path: "/etc/forklift-ui"
ui_configmap_name: "{{ ui_service_name }}-config"
ui_service_name: "{{ app_name }}-ui"
ui_deployment_name: "{{ ui_service_name }}"
ui_container_name: "{{ app_name }}-ui"
ui_container_limits_cpu: "100m"
ui_container_limits_memory: "800Mi"
ui_container_requests_cpu: "100m"
ui_container_requests_memory: "150Mi"
ui_route_name: "virt"
ui_meta_file_name: "meta.json"
