apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: forklift-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: The Konveyor Forklift Operator fully manages the deployment and life cycle of Forklift on OpenShift.
  displayName: Konveyor Forklift Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - migration
  links:
  - name: Forklift Operator
    url: https://forklift-operator.domain
  maintainers:
  - email: openshift-operators@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
